use MedBookDB;
insert into Users(FirstName,LastName,Email,Password,UserType) values('irinel', 'manolache', 'irinel.manolache@gmail.com', 'irinelpass', 1);
insert Location(City,StreenName,StreenNr) values('Iasi', 'Codrescu', '10');
insert Location(City,StreenName,StreenNr) values('Bucuresti', 'Bl. Mircea Voda', '50');
insert Location(City,StreenName,StreenNr) values('Cluj Napoca', 'Piezisei', '1');
insert Location(City,StreenName,StreenNr) values('Timisoara', 'Bl. Independentei', '3');
insert Location(City,StreenName,StreenNr) values('Iasi', 'Td. Vladimirescu', '20');

insert Specialization(Description) Values('Alergologie şi imunologie clinică');
insert into Specialization (Description) Values('Anestezie şi terapie intensivă');
insert into Specialization (Description) Values('Boli infecţioase');
insert into Specialization (Description) Values('Cardiologie');
insert into Specialization (Description) Values('Cardiologie pediatrică');
insert into Specialization (Description) Values('Dermatovenerologie');
insert into Specialization (Description) Values('Diabet zaharat, nutriţie şi boli metabolice');
insert into Specialization (Description) Values('Endocrinologie');
insert into Specialization (Description) Values('Expertiza medicală a capacităţii de muncă');
insert into Specialization (Description) Values('Farmacologie clinică');
insert into Specialization (Description) Values('Gastroenterologie');
insert into Specialization (Description) Values('Gastroenterologie pediatrică');
insert into Specialization (Description) Values('Genetică medicală');
insert into Specialization (Description) Values('Geriatrie şi gerontologie');
insert into Specialization (Description) Values('Hematologie');
insert into Specialization (Description) Values('Medicină de familie');
insert into Specialization (Description) Values('Medicină de urgenţă');
insert into Specialization (Description) Values('Medicină internă');
insert into Specialization (Description) Values('Medicină fizică şi de reabilitare');
insert into Specialization (Description) Values('Medicina muncii');
insert into Specialization (Description) Values('Medicină sportivă');
insert into Specialization (Description) Values('Nefrologie');
insert into Specialization (Description) Values('Nefrologie pediatrică');
insert into Specialization (Description) Values('Neonatologie');
insert into Specialization (Description) Values('Neurologie');
insert into Specialization (Description) Values('Neurologie pediatrică');
insert into Specialization (Description) Values('Oncologie medicală');
insert into Specialization (Description) Values('Oncologie şi hematologie pediatrică');
insert into Specialization (Description) Values('Pediatrie');
insert into Specialization (Description) Values('Pneumologie');
insert into Specialization (Description) Values('Pneumologie pediatrică');
insert into Specialization (Description) Values('Psihiatrie');
insert into Specialization (Description) Values('Psihiatrie pediatrică');
insert into Specialization (Description) Values('Radioterapie');
insert into Specialization (Description) Values('Reumatologie');
insert into Specialization (Description) Values('Chirurgie cardiovasculară');
insert into Specialization (Description) Values('Chirurgie generală');
insert into Specialization (Description) Values('Chirurgie orală şi maxilo-facială');
insert into Specialization (Description) Values('Chirurgie pediatrică');
insert into Specialization (Description) Values('Chirurgie plastică, estetică şi microchirurgie reconstructivă');
insert into Specialization (Description) Values('Chirurgie toracică');
insert into Specialization (Description) Values('Chirurgie vasculară');
insert into Specialization (Description) Values('Neurochirurgie');
insert into Specialization (Description) Values('Obstetrică-ginecologie');
insert into Specialization (Description) Values('Oftalmologie');
insert into Specialization (Description) Values('Ortopedie pediatrică');
insert into Specialization (Description) Values('Ortopedie şi traumatologie');
insert into Specialization (Description) Values('Otorinolaringologie');
insert into Specialization (Description) Values('Urologie');
insert into Specialization (Description) Values('Anatomie palogică');
insert into Specialization (Description) Values('Epidemiolog');
insert into Specialization (Description) Values('Igienă');
insert into Specialization (Description) Values('Medicină de laborator');
insert into Specialization (Description) Values('Medicină legală');
insert into Specialization (Description) Values('Medicină nucleară');
insert into Specialization (Description) Values('Microbiologie medicală');
insert into Specialization (Description) Values('Radiologie-imagistică medicală');
insert into Specialization (Description) Values('Sănătate publică şi management');
insert into Specialization (Description) Values('Chirurgie dento-alveolară');
insert into Specialization (Description) Values('Ortodonţie şi ortopedie dento-facială');
insert into Specialization (Description) Values('Endodonţie');
insert into Specialization (Description) Values('Parodontologie');
insert into Specialization (Description) Values('Pedodonţie');
insert into Specialization (Description) Values('Protetică dentară');

insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 1, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 3, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 4, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 5, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 6, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 7, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 8, 'Recumed', 'Servicii medicale private');
insert into MedicalService(UserId, LocationId, SpecializationId, Name, Description) values(1, 1, 9, 'Recumed', 'Servicii medicale private');
